<select id="country" name="pays" class="form-control" style="width: 236px;" >
   <option value="FRANCE">FRANCE</optio>
   <option value="ALLEMAGNE">ALLEMAGNE</ption>
   <option value="AUTRICHE">AUTRICHE</opton>
   <option value="BELGIQUE">BELGIQUE</optin>
   <option value="ESPAGNE">ESPAGNE</option>
   <option value="FINLANDE">FINLANDE</option>
   <option value="GRECE">GRECE</option>
   <option value="IRLANDE">IRLANDE</option>
   <option value="ITALIE">ITALIE</option>
   <option value="PORTUGAL">PORTUGAL</option>
   <option value="ROYAUME UNI">ROYAUME UNI</option>
   <option value="SUEDE">SUEDE</option>
   <option value="SUISSE">SUISSE</option>
   <option value="ALBANIE">ALBANIE</option>
   <option value="ANDORRE">ANDORRE</option>
   <option value="BIELORUSSIE">BIELORUSSIE</option>
   <option value="BOSNIE HERZEGOVINE">BOSNIE HERZEGOVINE</option>
   <option value="BULGARIE">BULGARIE</option>
   <option value="CROATIE">CROATIE</option>
   <option value="DANEMARK">DANEMARK</option>
   <option value="ESTONIE">ESTONIE</option>
   <option value="HONGRIE">HONGRIE</option>
   <option value="ISLANDE">ISLANDE</option>
   <option value="KOSOVO">KOSOVO</option>
   <option value="LETTONIE">LETTONIE</option>
   <option value="LIECHTENSTEIN">LIECHTENSTEIN</option>
   <option value="LITUANIE">LITUANIE</option>
   <option value="LUXEMBOURG">LUXEMBOURG</option>
   <option value="MACEDOINE">MACEDOINE</option>
   <option value="MOLDAVIE">MOLDAVIE</option>
   <option value="MONACO">MONACO</option>
   <option value="NORVEGE">NORVEGE</option>
   <option value="PAYS BAS">PAYS BAS</option>
   <option value="POLOGNE">POLOGNE</option>
   <option value="REPUBLIQUE TCHEQUE">REPUBLIQUE TCHEQUE</option>
   <option value="ROUMANIE">ROUMANIE</option>
   <option value="SLOVAQUIE">SLOVAQUIE</option>
   <option value="SLOVENIE">SLOVENIE</option>
   <option value="UKRAINE">UKRAINE</option>
   <option value="YOUGOSLAVIE">YOUGOSLAVIE</option>
   <option value="CANADA">CANADA</option>
   <option value="ETATS UNIS">ETATS UNIS</option>
   <option value="MEXIQUE">MEXIQUE</option>
   <option value="ARGENTINE">ARGENTINE</option>
   <option value="BOLIVIE">BOLIVIE</option>
   <option value="BRESIL">BRESIL</option>
   <option value="CHILIE">CHILIE</option>
   <option value="COLOMBIE">COLOMBIE</option>
   <option value="EQUATEUR">EQUATEUR</option>
   <option value="GUYANA">GUYANA</option>
   <option value="PEROU">PEROU</option>
   <option value="SURINAM">SURINAM</option>
   <option value="URUGUAY">URUGUAY</option>
   <option value="VENEZUELA">VENEZUELA</option>
   <option value="CARAIBES">CARAIBES</option>
   <option value="COSTA RICA">COSTA RICA</option>
   <option value="GUATEMALA">GUATEMALA</option>
   <option value="HONDURAS">HONDURAS</option>
   <option value="NICARAGUA">NICARAGUA</option>
   <option value="PANAMA">PANAMA</option>
   <option value="PARAGUAY">PARAGUAY</option>
   <option value="SALVADOR">SALVADOR</option>
   <option value="AUSTRALIE">AUSTRALIE</option>
   <option value="NOUVELLE ZELANDE">NOUVELLE ZELANDE</option>
   <option value="PAPOUASIE">PAPOUASIE</option>
   <option value="AFRIQUE DU SUD">AFRIQUE DU SUD</option>
   <option value="ALGERIE">ALGERIE</option>
   <option value="ANGOLA">ANGOLA</option>
   <option value="BENIN">BENIN</option>
   <option value="BURKINA FASO">BURKINA FASO</option>
   <option value="BURUNDI">BURUNDI</option>
   <option value="BOTSWANA">BOTSWANA</option>
   <option value="CAMEROUN">CAMEROUN</option>
   <option value="CONGO">CONGO</option>
   <option value="COTE D'IVOIRE">COTE D'IVOIRE</option>
   <option value="DJIBOUTI">DJIBOUTI</option>
   <option value="EGYPTE">EGYPTE</option>
   <option value="ERYTHREE">ERYTHREE</option>
   <option value="ETHIOPIE">ETHIOPIE</option>
   <option value="GABON">GABON</option>
   <option value="GAMBIE">GAMBIE</option>
   <option value="GHANA">GHANA</option>
   <option selected="selected " value="GUINEE">GUINEE</option>
   <option value="GUINEE BISSAU">GUINEE BISSAU</option>
   <option value="KENYA">KENYA</option>
   <option value="LIBERIA">LIBERIA</option>
   <option value="LIBYE">LIBYE</option>
   <option value="MADAGASCAR">MADAGASCAR</option>
   <option value="MALAWIE">MALAWIE</option>
   <option value="MALI">MALI</option>
   <option value="MAROC">MAROC</option>
   <option value="MAURITANIE">MAURITANIE</option>
   <option value="MOZAMBIQUE">MOZAMBIQUE</option>
   <option value="NAMIBIE">NAMIBIE</option>
   <option value="NIGER">NIGER</option>
   <option value="NIGERIA">NIGERIA</option>
   <option value="OUGANDA">OUGANDA</option>
   <option value="REP.CENTRAFRICAINE">REP.CENTRAFRICAINE</option>
   <option value="REP.DEM.DU CONGO">REP.DEM.DU CONGO</option>
   <option value="RWANDA">RWANDA</option>
   <option value="SENEGAL">SENEGAL</option>
   <option value="SIERRA LEONE">SIERRA LEONE</option>
   <option value="SOMALIE">SOMALIE</option>
   <option value="SOUDAN">SOUDAN</option>
   <option value="SWAZILAND">SWAZILAND</option>
   <option value="TANZANIE">TANZANIE</option>
   <option value="TCHAD">TCHAD</option>
   <option value="TUNISIE">TUNISIE</option>
   <option value="TOGO">TOGO</option>
   <option value="ZAMBIE">ZAMBIE</option>
   <option value="CAP-VERT">CAP-VERT</option>
   <option value="COMORES">COMORES</option>
   <option value="MAURICE">MAURICE</option>
   <option value="SEYCHELLES">SEYCHELLES</option>
   <option value="AFGHANISTAN">AFGHANISTAN</option>
   <option value="ARABIE SAOUDITE">ARABIE SAOUDITE</option>
   <option value="ARMENIE">ARMENIE</option>
   <option value="AZERBAIDJAN">AZERBAIDJAN</option>
   <option value="BANGLADESH">BANGLADESH</option>
   <option value="BIRMANIE">BIRMANIE</option>
   <option value="BOUTHAN">BOUTHAN</option>
   <option value="CAMBODGE">CAMBODGE</option>
   <option value="CHINE">CHINE</option>
   <option value="COREE DU NORD">COREE DU NORD</option>
   <option value="COREE DU SUD">COREE DU SUD</option>
   <option value="EMIRATS ARABES UNIS">EMIRATS ARABES UNIS</option>
   <option value="GEORGIE">GEORGIE</option>
   <option value="HONG KONG">HONG KONG</option>
   <option value="INDE">INDE</option>
   <option value="INDONESIE">INDONESIE</option>
   <option value="IRAN">IRAN</option>
   <option value="IRAK">IRAK</option>
   <option value="ISRAEL">ISRAEL</option>
   <option value="JAPON">JAPON</option>
   <option value="JORDANIE">JORDANIE</option>
   <option value="KAZAKHSTAN">KAZAKHSTAN</option>
   <option value="KIRGHIZSTAN">KIRGHIZSTAN</option>
   <option value="KOWEIT">KOWEIT</option>
   <option value="LAOS">LAOS</option>
   <option value="LIBAN">LIBAN</option>
   <option value="MALAISIE">MALAISIE</option>
   <option value="MONGOLIE">MONGOLIE</option>
   <option value="NEPAL">NEPAL</option>
   <option value="OMAN">OMAN</option>
   <option value="OUZBEKISTAN">OUZBEKISTAN</option>
   <option value="PAKISTAN">PAKISTAN</option>
   <option value="PHILIPINES">PHILIPINES</option>
   <option value="QATAR">QATAR</option>
   <option value="RUSSIE">RUSSIE</option>
   <option value="TADJIKISTAN">TADJIKISTAN</option>
   <option value="TAIWAN">TAIWAN</option>
   <option value="THAILANDE">THAILANDE</option>
   <option value="TURKMENISTAN">TURKMENISTAN</option>
   <option value="TURQUIE">TURQUIE</option>
   <option value="VIETNAM">VIETNAM</option>
   <option value="YEMEN">YEMEN</option>
</select>